$mysql_script = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "CREATE USER 'mysqluser'@'%' IDENTIFIED BY 'pass';"
    mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'mysqluser'@'%';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"    
    #config.vm.boot_timeout = 600

    ### Network ###
    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "public_network", ip: "192.168.15.25"
        
    #config.vm.network "private_network", ip: "192.168.16.10"
    #config.vm.network "private_network", type: "dhcp"    
    
    ### Provision ###
    config.vm.provision "shell", 
        inline: "cat /configs/bionic_key.pub >> .ssh/authorized_keys"
    
    config.vm.provision "shell", inline: $mysql_script

    config.vm.provision "shell", 
        inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
            
    config.vm.provision "shell", 
        inline: "service mysql restart"
    
    ### Synced Folder ###
    config.vm.synced_folder "./configs", "/configs"
    config.vm.synced_folder ".", "/vagrant", disabled: true
end