Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    #config.vm.boot_timeout = 600
    config.vm.network "forwarded_port", guest: 80, host: 8080    
    config.vm.network "forwarded_port", guest: 80, host: 80
    
    #config.vm.network "private_network", ip: "192.168.16.10"
    #config.vm.network "private_network", type: "dhcp"

    config.vm.network "public_network", ip: "192.168.15.25"
end