$mysql_script = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "CREATE USER 'mysqluser'@'%' IDENTIFIED BY 'pass';"
    mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'mysqluser'@'%';"
SCRIPT

Vagrant.configure("2") do |config|   
    config.vm.box = "ubuntu/bionic64"
    #config.vm.boot_timeout = 600

    config.vm.define "mysqldb" do |mysql|        
        ### Network ###
        mysql.vm.network "public_network", ip: "192.168.15.25"            
        #mysql.vm.network "private_network", ip: "192.168.16.10"
        #mysql.vm.network "private_network", type: "dhcp"    
        
        ### Provision ###
        mysql.vm.provision "shell", 
            inline: "cat /configs/bionic_key.pub >> .ssh/authorized_keys"
        
        mysql.vm.provision "shell", inline: $mysql_script

        mysql.vm.provision "shell", 
            inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
                
        mysql.vm.provision "shell", 
            inline: "service mysql restart"
        
        ### Synced Folder ###
        mysql.vm.synced_folder "./configs", "/configs"
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define "phpweb" do |php|
        php.vm.network "forwarded_port", guest: 8888, host: 8888
        php.vm.network "public_network", ip: "192.168.15.26"

        php.vm.provision "shell", 
            inline: "apt-get update && apt-get install -y puppet"

        php.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests/phpweb"
            puppet.manifest_file = "phpweb.pp"
        end
    end
end